added lab 1 tasks
synchro-p/NSU-OOP pull request #1
Opened 2021-09-24 04:42 UTC by synchro-p

first solutions for tasks 1.1.1 and 1.1.2

2021-09-24 06:43 UTC, molo4evan requested changes

2021-09-24 06:43 UTC, molo4evan commented on Task-1-1-1/.idea/compiler.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Поправь `gitignore`, я не готов продираться через все вспомогательные файлы

2021-09-24 10:40 UTC, molo4evan approved these changes

2021-09-24 10:50 UTC, molo4evan commented
Зачем нужен `Task-1-1-2/src - Ярлык.lnk`? :)

2021-09-24 12:23 UTC, molo4evan commented on Task-1-1-1/src/main/java/nsu/fit/oop/heapsort/Heapsort.java
> +            arr[0] = arr[end];
Прикрути `swap`

2021-09-24 12:23 UTC, molo4evan commented on Task-1-1-1/src/main/java/nsu/fit/oop/heapsort/Heapsort.java
> +    public static Integer[] heapsort(String inp){
Добавь `heapsort` на массивах

2021-09-24 12:23 UTC, molo4evan commented on Task-1-1-1/src/main/java/nsu/fit/oop/heapsort/Heapsort.java
> +
А куда тут отступы


поехали?

2021-09-24 12:23 UTC, molo4evan commented on Task-1-1-1/src/test/java/nsu/fit/oop/heapsortTests/Tests.java
> +    @ValueSource (strings = {"{1,2,3,4,5}","{1,4,5,2,3}",
Добавь `methodSource` с генерацией массива или захардкоженными массивами, опорный массив для сравнения получай копированием и стандартной сортировкой

(подсказка: см. `Arrays`)

2021-09-24 12:23 UTC, molo4evan commented on Task-1-1-1/src/test/java/nsu/fit/oop/heapsortTests/Tests.java
> +public class Tests {
Добавь отдельные unit-тесты на heapsort на массивах и на конвертацию строка-массив

2021-09-24 12:23 UTC, molo4evan commented on Task-1-1-2/src/main/java/nsu/fit/oop/substring/Substring.java
> +        String filename = sys.nextLine(),searchFor = sys.nextLine();
Хотя бы пробел между выражениями, а лучше с новой строки все-таки, это разные операции чтения разных строк, читаемее будет

2021-09-24 12:23 UTC, molo4evan commented on Task-1-1-2/src/main/java/nsu/fit/oop/substring/Substring.java
> +        if (filename.equals("")) throw new IllegalArgumentException("empty filename");
А если не пусто, а null?

2021-09-24 12:23 UTC, molo4evan commented on Task-1-1-2/src/main/java/nsu/fit/oop/substring/Substring.java
> +                if ((int)toCheck[l-1] > 0 && (int)toCheck[l-1] < 20 && (int)next > 0 && (int)next<20){
Это тут вообще зачем?

2021-09-24 12:23 UTC, molo4evan commented on Task-1-1-2/src/main/java/nsu/fit/oop/substring/Substring.java
> +                if (Arrays.equals(query.toCharArray(), toCheck)){
Я, в общем, не совсем понял, это самописный алгоритм или взятый откуда-то, но выглядит не особенно эффективно)

Так что нужно или предоставить убедительно рассчитанную асимптотику, которая показывает, что он эффективен (хотя насчет эффективности использования `Arrays.equals` в алгоритме поиска подстроки я сомневаюсь), или переписать на каком-нибудь из классических алгоритмов (можно просто на вики забить "поиск подстроки")

2021-09-24 12:23 UTC, molo4evan commented on Task-1-1-2/src/test/java/nsu/fit/oop/substringTests/Tests.java
> +    void wrongFile(String string){
Дополни названия тестов префиксом `test`: `testWrongFiles`, `testSuperLong`...

2021-09-24 12:23 UTC, molo4evan commented on Task-1-1-2/src/test/java/nsu/fit/oop/substringTests/Tests.java
> +        } catch (IllegalArgumentException e) {
См. `assertThrows`

2021-09-24 12:23 UTC, molo4evan commented on Task-1-1-2/src/test/java/nsu/fit/oop/substringTests/Tests.java
> +        assert(Substring.search("1.txt","s").equals("{8192}"));
Переделать на JUnit Assertions (`assertThat`, `assertThrows`, etc.)

Или на ассертах из AssertJ (см. ссылку в гисте)

2021-09-24 12:23 UTC, molo4evan commented on Task-1-1-2/src/test/java/nsu/fit/oop/substringTests/Tests.java
> +    void superLong(){
Этот и ниже тесты тоже заменить `ParameterizedTest` (будет 3 параметра, можно использовать станартный класс из parameterized - `Arguments`) (см. тутор по parameterized в гисте)

2021-09-24 12:41 UTC, synchro-p commented on Task-1-1-2/src/main/java/nsu/fit/oop/substring/Substring.java
> +                if (Arrays.equals(query.toCharArray(), toCheck)){
Да, самописный. Пока вы не написали, даже не думал, что настолько огромное количество алгоритмов существует. Перепишу

2021-09-24 12:44 UTC, synchro-p commented on Task-1-1-2/src/main/java/nsu/fit/oop/substring/Substring.java
> +                if ((int)toCheck[l-1] > 0 && (int)toCheck[l-1] < 20 && (int)next > 0 && (int)next<20){
Игнорировать идущие подряд специальные символы. Например, при простом переводе строки с файла сразу ставятся 10ый и 13ый, комбинация смены строки и перевода каретки на начало. Из-за специфики алгоритма это сразу его клало. Наверное, на более адекватные не должно влиять особенно

2021-09-24 17:43 UTC, synchro-p commented on Task-1-1-1/src/main/java/nsu/fit/oop/heapsort/Heapsort.java
> +            arr[0] = arr[end];
Не понимаю, какой именно `swap` использовать - самописный работает либо так же, либо каким-то неочевидным способом через логические операции, а встроенный - только для коллекций, менять объекты туда-сюда по 2 раза вряд ли хорошо для времени работы

2021-09-24 18:09 UTC, molo4evan commented on Task-1-1-1/src/main/java/nsu/fit/oop/heapsort/Heapsort.java
> +            arr[0] = arr[end];
Просто хочу, чтобы ты вынес код, работает так же, да, но в данном случае речь не об эффективности, а об уменьшении дублирования кода. На самом деле не критично, в данном случае считай придиркой (но все равно переделай) :)

2021-09-24 18:13 UTC, molo4evan commented on Task-1-1-2/src/main/java/nsu/fit/oop/substring/Substring.java
> +                if ((int)toCheck[l-1] > 0 && (int)toCheck[l-1] < 20 && (int)next > 0 && (int)next<20){
Вообще для подобных целей можно использовать некоторые методы `Character` (не уверен, что есть подходящий для данного случая, но покопаться в доках можно), у него есть куча проверок типа `isDigit`, `isWhitespace`, etc.

Тред можешь закрывать.

2021-09-26 15:56 UTC, synchro-p commented on Task-1-1-2/src/main/java/nsu/fit/oop/substring/Substring.java
> +                if (Arrays.equals(query.toCharArray(), toCheck)){
Исходя из условия (файл может быть сильно больше буфера, искомая подстрока всегда сильно меньше) решил взять примитивный алгоритм, у него сложность О(H*N) в худшем случае (H, N - соответственно размер строки, в которой ищем и размер искомой подстроки), что при нашем условии должно неплохо работать. Переделываю

2021-09-29 17:51 UTC, molo4evan commented on Task-1-1-1/src/test/java/nsu/fit/oop/heapsortTests/Tests.java
> +    @MethodSource ("arrayGenerator")
Пробел не нужен, это параметры аннтоации, но, в целом, ИМХО, не критично, можешь поправить, можешь просто тред закрыть

2021-09-29 18:07 UTC, molo4evan commented on Task-1-1-2/src/main/java/nsu/fit/oop/substring/Substring.java
>          if (query.equals("")) throw new IllegalArgumentException("empty query");
`||`

2021-09-29 18:07 UTC, molo4evan commented on Task-1-1-2/src/main/java/nsu/fit/oop/substring/Substring.java
> +    public static String search(String filename, String query) throws FileNotFoundException {
А теперь самое интересное (на самом деле, прошу прощения, что не добавил замечание раньше).

Сейчас метод очень не универсален, мы можем искать исключительно в файлах по абсолютному пути.

В подобных кейсах хорошая практика - принимать, например, `Reader`, тогда мы сможем сунуть в функцию и файл (`FileReader`), и строку (`StringReader`), и какой-то другой поток данных. 

Абстрагирование - фундамент ООП :)

2021-09-29 18:07 UTC, molo4evan commented on Task-1-1-2/src/main/java/nsu/fit/oop/substring/Substring.java
> +            throw new FileNotFoundException("no such file in directory");
Зачем оборачивать `FileNotFoundException` в другой `FileNotFoundException`? У стандартного некорректный вывод?

![image](https://user-images.githubusercontent.com/25470436/135333339-17f169b2-aadd-4025-a2d3-b2df5cdcb2cb.png)

2021-09-29 18:07 UTC, molo4evan commented on Task-1-1-2/src/main/java/nsu/fit/oop/substring/Substring.java
> +            char c = scanner.next().charAt(0);
Вообще, `Scanner` - не лучшее решение для посимвольной работы с текстом. Есть `BufferedReader`.

2021-09-29 18:07 UTC, molo4evan commented on Task-1-1-2/src/main/java/nsu/fit/oop/substring/Substring.java
> +                if (Arrays.equals(query.toCharArray(), toCheck)){
С поиском подстрок, кстати, роль может играть не только формальная асимптотика, но и эмпирика разных типов входных данных. Если почитать про плюсы и минусы конкретных алгоритмов, то при схожей асимптотике они могут работать лучше или хуже на текстах определенной специфики. 

Предлагаю реализовать (а заодно и познакомиться на практике) какой-нибудь из классических алгоритмов: Рабина-Карпа, Ахо-Корасик, Бойера-Мура, например, или другой на выбор, на той же википедии перечислены самые популярные.

Тот же Ахо-Корасик, насколько я помню, в юниксовом grep используется, можешь взять его.

2021-09-29 18:08 UTC, molo4evan requested changes

2021-09-29 18:08 UTC, molo4evan commented on Task-1-1-2/src/main/java/nsu/fit/oop/substring/Substring.java
> +            for (int i = 1; i<query.length()&& scanner.hasNext(); i++){
Беды с пробелами

2021-10-01 04:03 UTC, synchro-p commented on Task-1-1-2/src/main/java/nsu/fit/oop/substring/Substring.java
> +            throw new FileNotFoundException("no such file in directory");
Чтобы проставить ему своё сообщение (то, что `e.getMessage()`)

2021-10-01 04:18 UTC, synchro-p commented on Task-1-1-2/src/main/java/nsu/fit/oop/substring/Substring.java
> +            throw new FileNotFoundException("no such file in directory");
Откатил эти изменения

2021-10-01 04:19 UTC, synchro-p commented on Task-1-1-2/src/main/java/nsu/fit/oop/substring/Substring.java
>          if (query.equals("")) throw new IllegalArgumentException("empty query");
Разделил на 2 exception с разными сообщениями

2021-10-01 04:23 UTC, synchro-p commented on Task-1-1-2/src/main/java/nsu/fit/oop/substring/Substring.java
> +            for (int i = 1; i<query.length()&& scanner.hasNext(); i++){
Откатил

2021-10-01 04:30 UTC, synchro-p commented on Task-1-1-2/src/main/java/nsu/fit/oop/substring/Substring.java
> +    public static String search(String filename, String query) throws FileNotFoundException {
Слишком сильно концентрируюсь на задаче с конкретными входными данными, после Си на первом курсе сложно)

2021-10-01 04:36 UTC, synchro-p commented
Проверьте, пожалуйста, на одной ли мы странице. Немного с файлами путаница вышла по моей вине. Сейчас, как я понял, 3 проблемы:
1. Плохой алгоритм
2. Scanner вместо BufferedReader
3. Передаём в функцию строку, а не Reader
Если есть другие нарекания или вернулись старые, пожалуйста, откройте новые треды. Прошу простить, с Гитом пока что не идеально работаю

2021-10-01 07:07 UTC, molo4evan commented on Task-1-1-2/src/main/java/nsu/fit/oop/substring/Substring.java
> +    public static String search(String filename, String query){
Строка из вхождений - тоже не самый удобный вариант, кому нужно, тот сам все выведет или в строку преобразует. Лучше возвращать массив индексов вхождений.

2021-10-01 07:09 UTC, molo4evan commented on Task-1-1-2/src/main/java/nsu/fit/oop/substring/Substring.java
> +                if (Arrays.equals(query.toCharArray(), toCheck)){
С поиском подстрок, кстати, роль может играть не только формальная асимптотика, но и эмпирика разных типов входных данных. Если почитать про плюсы и минусы конкретных алгоритмов, то при схожей асимптотике они могут работать лучше или хуже на текстах определенной специфики.

Плюс многие алгоритмы при несовпадении префикса шаблона сдвигают поиск сразу на размер префикса, а не на 1 символ, и при большом шаблоне в зависимости от вида данных это может существенно ускорять поиск.

Предлагаю реализовать (а заодно и познакомиться на практике) какой-нибудь из классических алгоритмов: Рабина-Карпа, Ахо-Корасик, Бойера-Мура, например, или другой на выбор, на той же википедии перечислены самые популярные.

Тот же Ахо-Корасик, насколько я помню, в юниксовом grep используется, можешь взять его.

2021-10-01 07:12 UTC, molo4evan commented
> 
> 
> Проверьте, пожалуйста, на одной ли мы странице. Немного с файлами путаница вышла по моей вине. Сейчас, как я понял, 3 проблемы:
> 
>     1. Плохой алгоритм
> 
>     2. Scanner вместо BufferedReader
> 
>     3. Передаём в функцию строку, а не Reader
> 
> 
> Если есть другие нарекания или вернулись старые, пожалуйста, откройте новые треды. Некоторые открытые треды пофиксил. Прошу простить, с Гитом пока что не идеально работаю По идее, 1 задание не изменял, с ним открытых тредов нет и не должно было появиться. Всё вышесказанное относится ко второму заданию. В теории, возможно лучше будет закрыть этот пулл-реквест и открыть новый

Да, по проблемам все так, добавил еще 1 замечание, насчет возвращаемого значения. Треды постарался почистить (гитхаб местами странно себя ведет).

Действительно, как вариант, можешь перенести код по 1.2 в новую ветку, по первой нареканий нет, но тогда придется переносить туда замечания по 1.2. Как вариант, можешь открыть новый PR с уже исправленными замечаниями, а тут редиректнуть туда, тогда этот PR можно будет считать закрытым (после, возможно, обсуждения 1.1 на семинаре :) )

2021-10-01 08:01 UTC, synchro-p commented
@molo4evan Эту ветку закрываю, в [lab-1-2](https://github.com/synchro-p/NSU-OOP/pull/2) теперь находятся все треды и правки. Первая задача (сортировка) готова к мерджу после 01.10, над второй задачей работу веду в новой ветке. Текущие недочёты туда перенес.

2021-10-01 08:01 UTC, closed without merging